


/* Generated by glib-mkenums. Do not edit */

#ifndef __NM_MODEM_ENUM_TYPES_H__
#define __NM_MODEM_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
GType nm_modem_error_get_type (void) G_GNUC_CONST;
#define NM_TYPE_MODEM_ERROR (nm_modem_error_get_type ())
GType nm_modem_state_get_type (void) G_GNUC_CONST;
#define NM_TYPE_MODEM_STATE (nm_modem_state_get_type ())
G_END_DECLS

#endif /* __NM_MODEM_ENUM_TYPES_H__ */



