usr/sbin/NetworkManager
usr/bin/nm-online
usr/bin/nmcli
usr/bin/nmtui*
usr/lib/NetworkManager/nm-dhcp-helper
usr/lib/NetworkManager/nm-dispatcher
usr/lib/NetworkManager/nm-avahi-autoipd.action
usr/lib/*/NetworkManager/libnm-settings-plugin-ifupdown.so
usr/lib/*/NetworkManager/libnm-settings-plugin-ofono.so
usr/lib/*/NetworkManager/libnm-device-plugin-*.so
usr/lib/*/NetworkManager/libnm-wwan.so
usr/lib/pppd/*/*.so
usr/share/locale/
usr/share/man/
usr/share/dbus-1/system-services/
usr/share/polkit-1/
usr/share/bash-completion/
etc/dbus-1/system.d/org.freedesktop.NetworkManager.conf
etc/dbus-1/system.d/nm-dispatcher.conf
etc/dbus-1/system.d/nm-avahi-autoipd.conf
etc/dbus-1/system.d/nm-ofono.conf
etc/NetworkManager/dispatcher.d/
lib/udev/rules.d/*.rules
lib/systemd/system/NetworkManager.service
lib/systemd/system/NetworkManager-dispatcher.service
lib/systemd/system/NetworkManager-wait-online.service
debian/NetworkManager.conf etc/NetworkManager/
debian/org.freedesktop.NetworkManager.pkla var/lib/polkit-1/localauthority/10-vendor.d/
debian/60-network-manager.rules usr/share/polkit-1/rules.d/
debian/source_network-manager.py /usr/share/apport/package-hooks/
