


/* Generated by glib-mkenums. Do not edit */

#ifndef __NM_CORE_TESTS_ENUM_TYPES_H__
#define __NM_CORE_TESTS_ENUM_TYPES_H__

#include <glib-object.h>

G_BEGIN_DECLS
GType nm_test_general_bool_enum_get_type (void) G_GNUC_CONST;
#define NM_TYPE_TEST_GENERAL_BOOL_ENUM (nm_test_general_bool_enum_get_type ())
GType nm_test_general_meta_flags_get_type (void) G_GNUC_CONST;
#define NM_TYPE_TEST_GENERAL_META_FLAGS (nm_test_general_meta_flags_get_type ())
GType nm_test_general_color_flags_get_type (void) G_GNUC_CONST;
#define NM_TYPE_TEST_GENERAL_COLOR_FLAGS (nm_test_general_color_flags_get_type ())
G_END_DECLS

#endif /* __NM_CORE_TESTS_ENUM_TYPES_H__ */



